### PR TITLE
ERC20: Add support for BTC2x-FLI

### PR DESCRIPTION
**Pull request by jhuntbach-bc**

### CODE REVIEW

**Comment by blockchain-concourse-platform** [comment]
[+] Running checks...


-  ⚠️  [BCH, COIN]: minWithdrawal 5460 -> $0.010 not in the $0.01-$10 USD range
-  ⚠️  [BSV, COIN]: No logo
-  ⚠️  [CEUR, CELO_TOKEN]: displayed as: cEUR
-  ⚠️  [CLOUT, COIN]: displayed as: DESO
-  ⚠️  [CLOUT, COIN]: minWithdrawal 2000 -> $0.000 not in the $0.01-$10 USD range
-  ⚠️  [CUSD, CELO_TOKEN]: displayed as: cUSD
-  ⚠️  [DGLD, COIN]: minWithdrawal 5460 -> $0.010 not in the $0.01-$10 USD range
-  ⚠️  [LTC, COIN]: minWithdrawal 5460 -> $0.003 not in the $0.01-$10 USD range
-  ⚠️  [PAX, ERC20]: displayed as: USDP
-  ⚠️  [RENBTC, ERC20]: displayed as: renBTC

**Comment by jhuntbach-bc** [comment]
I just checked trustwallet and they do seem to have this token listed already: https://github.com/trustwallet/assets/blob/a3823f660dd68e0fe99944e931142360cf06e360/blockchains/ethereum/assets/0x0B498ff89709d3838a063f1dFA463091F9801c2b/logo.png
Any idea why it's not already in erc20-tokens.json?

**Comment by pablojorge** [comment]
> I just checked trustwallet and they do seem to have this token listed already: https://github.com/trustwallet/assets/tree/a3823f660dd68e0fe99944e931142360cf06e360/blockchains/ethereum/assets/0x0B498ff89709d3838a063f1dFA463091F9801c2b Any idea why it's not in erc20-tokens.json then?

Because we need to periodically update this repo (see https://github.com/blockchain/coin-definitions#updating). Can you give a try to that first? Note that as mentioned there, many times this generates conflicts, and it requires manual intervention by extending the `denylist.txt` file with those entries we _don't_ want to keep

**Comment by jhuntbach-bc** [comment]
Closing this PR because we don't currently support tokens with non-alphanumeric characters in the `symbol`

**Pull request closed without merging**
