### PR TITLE
CON-2278 chore(CLOUT): rename to DESO

### PR DESCRIPTION
**Pull request by ndcotta-bc**
also change logo

DO NOT MERGE UNTIL SEPT20

### CODE REVIEW

**Comment by blockchain-concourse-platform** [comment]
[+] Running checks...


-  ⚠️  [BSV, COIN]: No logo
-  ⚠️  [CLOUT, COIN]: displayed as: DESO
-  ⚠️  [CLOUT, COIN]: minWithdrawal 2000 -> $0.000 not in the $0.01-$10 USD range
-  ⚠️  [DGLD, COIN]: minWithdrawal 5460 -> $0.010 not in the $0.01-$10 USD range
-  ⚠️  [DOGE, COIN]: minWithdrawal 5460 -> $0.000 not in the $0.01-$10 USD range
-  ⚠️  [LTC, COIN]: minWithdrawal 5460 -> $0.010 not in the $0.01-$10 USD range
-  ⚠️  [PAX, ERC20]: displayed as: USDP
-  ⚠️  [TBTC, ERC20]: minWithdrawal 300000000000000.0 -> $14.857 not in the $0.01-$10 USD range

**Review by pablojorge — APPROVED** [review]

**Comment by blockchain-concourse-platform** [comment]
[+] Running checks...


-  ⚠️  [BSV, COIN]: No logo
-  ⚠️  [CLOUT, COIN]: displayed as: DESO
-  ⚠️  [CLOUT, COIN]: minWithdrawal 2000 -> $0.000 not in the $0.01-$10 USD range
-  ⚠️  [DGLD, COIN]: minWithdrawal 5460 -> $0.010 not in the $0.01-$10 USD range
-  ⚠️  [DOGE, COIN]: minWithdrawal 5460 -> $0.000 not in the $0.01-$10 USD range
-  ⚠️  [LTC, COIN]: minWithdrawal 5460 -> $0.010 not in the $0.01-$10 USD range
-  ⚠️  [PAX, ERC20]: displayed as: USDP
-  ⚠️  [TBTC, ERC20]: minWithdrawal 300000000000000.0 -> $14.833 not in the $0.01-$10 USD range

**Comment by blockchain-concourse-platform** [comment]
[+] Running checks...


-  ⚠️  [BSV, COIN]: No logo
-  ⚠️  [CLOUT, COIN]: displayed as: DESO
-  ⚠️  [CLOUT, COIN]: minWithdrawal 2000 -> $0.000 not in the $0.01-$10 USD range
-  ⚠️  [DGLD, COIN]: minWithdrawal 5460 -> $0.010 not in the $0.01-$10 USD range
-  ⚠️  [DOGE, COIN]: minWithdrawal 5460 -> $0.000 not in the $0.01-$10 USD range
-  ⚠️  [PAX, ERC20]: displayed as: USDP
-  ⚠️  [TBTC, ERC20]: minWithdrawal 300000000000000.0 -> $14.601 not in the $0.01-$10 USD range

**Review by mpfluger — APPROVED** [review]

**Comment by blockchain-concourse-platform** [comment]
[+] Running checks...


-  ⚠️  [BSV, COIN]: No logo
-  ⚠️  [CLOUT, COIN]: displayed as: DESO
-  ⚠️  [CLOUT, COIN]: minWithdrawal 2000 -> $0.000 not in the $0.01-$10 USD range
-  ⚠️  [DGLD, COIN]: minWithdrawal 5460 -> $0.009 not in the $0.01-$10 USD range
-  ⚠️  [DOGE, COIN]: minWithdrawal 5460 -> $0.000 not in the $0.01-$10 USD range
-  ⚠️  [LTC, COIN]: minWithdrawal 5460 -> $0.009 not in the $0.01-$10 USD range
-  ⚠️  [PAX, ERC20]: displayed as: USDP
-  ⚠️  [TBTC, ERC20]: minWithdrawal 300000000000000.0 -> $13.335 not in the $0.01-$10 USD range

**Comment by blockchain-concourse-platform** [comment]
[+] Running checks...


-  ⚠️  [BSV, COIN]: No logo
-  ⚠️  [CLOUT, COIN]: displayed as: DESO
-  ⚠️  [CLOUT, COIN]: minWithdrawal 2000 -> $0.000 not in the $0.01-$10 USD range
-  ⚠️  [DGLD, COIN]: minWithdrawal 5460 -> $0.009 not in the $0.01-$10 USD range
-  ⚠️  [DOGE, COIN]: minWithdrawal 5460 -> $0.000 not in the $0.01-$10 USD range
-  ⚠️  [LTC, COIN]: minWithdrawal 5460 -> $0.009 not in the $0.01-$10 USD range
-  ⚠️  [TBTC, ERC20]: minWithdrawal 300000000000000.0 -> $13.110 not in the $0.01-$10 USD range

**Pull request merged**
