### PR TITLE
chore(CI): write pipeline

### PR DESCRIPTION
**Pull request by ndcotta-bc**

### CODE REVIEW

**Review by mpfluger — APPROVED** [review]

**Review by pablojorge — APPROVED** [review]

**Review by pablojorge — DISMISSED** [review]

**Comment by blockchain-concourse-platform** [comment]
## Coin Definition Check Result
[+] Running checks...

**Comment by blockchain-concourse-platform** [comment]
## Coin Definition Check Result
[+] Running checks...

**Comment by blockchain-concourse-platform** [comment]
## Coin Definition Check Result
[+] Running checks...

**Comment by blockchain-concourse-platform** [comment]
## Coin Definition Check Result
[+] Running checks... ⚠️ [BSV, COIN]: No logo ⚠️ [CLOUT, COIN]: minWithdrawal 2000 -> $0.000 not in the $0.01-$10 USD range ⚠️ [DGLD, COIN]: minWithdrawal 5460 -> $0.010 not in the $0.01-$10 USD range ⚠️ [DOGE, COIN]: minWithdrawal 5460 -> $0.000 not in the $0.01-$10 USD range ⚠️ [TBTC, ERC20]: minWithdrawal 300000000000000.0 -> $14.169 not in the $0.01-$10 USD range

**Comment by blockchain-concourse-platform** [comment]
## Coin Definition Check Result
[+] Running checks... ⚠️ [BSV, COIN]: No logo ⚠️ [CLOUT, COIN]: minWithdrawal 2000 -> $0.000 not in the $0.01-$10 USD range ⚠️ [DGLD, COIN]: minWithdrawal 5460 -> $0.010 not in the $0.01-$10 USD range ⚠️ [DOGE, COIN]: minWithdrawal 5460 -> $0.000 not in the $0.01-$10 USD range ⚠️ [PAX, ERC20]: displayed as: USDP ⚠️ [TBTC, ERC20]: minWithdrawal 300000000000000.0 -> $14.318 not in the $0.01-$10 USD range

**Comment by blockchain-concourse-platform** [comment]
## Coin Definition Check Result
[+] Running checks... - ⚠️ [BSV, COIN]: No logo - ⚠️ [CLOUT, COIN]: minWithdrawal 2000 -> $0.000 not in the $0.01-$10 USD range - ⚠️ [DGLD, COIN]: minWithdrawal 5460 -> $0.010 not in the $0.01-$10 USD range - ⚠️ [DOGE, COIN]: minWithdrawal 5460 -> $0.000 not in the $0.01-$10 USD range - ⚠️ [PAX, ERC20]: displayed as: USDP - ⚠️ [TBTC, ERC20]: minWithdrawal 300000000000000.0 -> $14.383 not in the $0.01-$10 USD range

**Comment by blockchain-concourse-platform** [comment]
[+] Running checks...

-  ⚠️  [BSV, COIN]: No logo

-  ⚠️  [CLOUT, COIN]: minWithdrawal 2000 -> $0.000 not in the $0.01-$10 USD range

-  ⚠️  [DGLD, COIN]: minWithdrawal 5460 -> $0.010 not in the $0.01-$10 USD range

-  ⚠️  [DOGE, COIN]: minWithdrawal 5460 -> $0.000 not in the $0.01-$10 USD range

-  ⚠️  [PAX, ERC20]: displayed as: USDP

-  ⚠️  [TBTC, ERC20]: minWithdrawal 300000000000000.0 -> $14.380 not in the $0.01-$10 USD range

**Comment by blockchain-concourse-platform** [comment]
[+] Running checks...

-  ⚠️  [BSV, COIN]: No logo

-  ⚠️  [CLOUT, COIN]: minWithdrawal 2000 -> $0.000 not in the $0.01-$10 USD range

-  ⚠️  [DGLD, COIN]: minWithdrawal 5460 -> $0.010 not in the $0.01-$10 USD range

-  ⚠️  [DOGE, COIN]: minWithdrawal 5460 -> $0.000 not in the $0.01-$10 USD range

-  ⚠️  [PAX, ERC20]: displayed as: USDP

-  ⚠️  [TBTC, ERC20]: minWithdrawal 300000000000000.0 -> $14.380 not in the $0.01-$10 USD range

**Comment by blockchain-concourse-platform** [comment]
[+] Running checks...


-  ⚠️  [BSV, COIN]: No logo
-  ⚠️  [CLOUT, COIN]: minWithdrawal 2000 -> $0.000 not in the $0.01-$10 USD range
-  ⚠️  [DGLD, COIN]: minWithdrawal 5460 -> $0.010 not in the $0.01-$10 USD range
-  ⚠️  [DOGE, COIN]: minWithdrawal 5460 -> $0.000 not in the $0.01-$10 USD range
-  ⚠️  [PAX, ERC20]: displayed as: USDP
-  ⚠️  [TBTC, ERC20]: minWithdrawal 300000000000000.0 -> $14.336 not in the $0.01-$10 USD range

**Review by pablojorge — APPROVED** [review]

**Review by pablojorge — APPROVED** [review]

**Comment by blockchain-concourse-platform** [comment]
[+] Running checks...


-  ⚠️  [BSV, COIN]: No logo
-  ⚠️  [CLOUT, COIN]: minWithdrawal 2000 -> $0.000 not in the $0.01-$10 USD range
-  ⚠️  [DGLD, COIN]: minWithdrawal 5460 -> $0.010 not in the $0.01-$10 USD range
-  ⚠️  [DOGE, COIN]: minWithdrawal 5460 -> $0.000 not in the $0.01-$10 USD range
-  ⚠️  [PAX, ERC20]: displayed as: USDP
-  ⚠️  [TBTC, ERC20]: minWithdrawal 300000000000000.0 -> $14.336 not in the $0.01-$10 USD range

**Pull request merged**
