### PR TITLE
Add file with ETH holding addresses for HWS

### PR DESCRIPTION
**Pull request by matsjj**
The way to confirm the addresses is to query the database for

```
select client_id, address from address where currency_id = 2 and type = 'HOLDING' and derivation_index = 2147483647 order by client_id asc
```

and then cross correlating it with the clients in the applications list

https://github.com/blockchain/applications/blob/master/production/hot-wallet/environment.template#L169

### CODE REVIEW

**Comment by blockchain-concourse-platform** [comment]
[+] Running checks...


-  ⚠️  [BSV, COIN]: No logo
-  ⚠️  [CEUR, CELO_TOKEN]: displayed as: cEUR
-  ⚠️  [CLOUT, COIN]: displayed as: DESO
-  ⚠️  [CLOUT, COIN]: minWithdrawal 2000 -> $0.000 not in the $0.01-$10 USD range
-  ⚠️  [CUSD, CELO_TOKEN]: displayed as: cUSD
-  ⚠️  [DGLD, COIN]: minWithdrawal 5460 -> $0.010 not in the $0.01-$10 USD range
-  ⚠️  [PAX, ERC20]: displayed as: USDP

**Comment by ndcotta-bc** [comment]
I don't know if you have discussed with @mpfluger or @pablojorge but I am not sure this repo is the right place for this info

**Comment by matsjj** [comment]
Yeah we did discuss a few options, but this one seemed like the most sensible. 
These addresses have not changed in 3 years and are unlikely to change going forward. I would even consider hardcoding them in the clients, but that would be too extreme. 
@ndcotta-bc I'm open to alternatives if you have an easy way of getting these to the clients though! :)

**Comment by ndcotta-bc** [comment]
If what you want is to expose this to the web, an http server that calls the DB seems to be the proper way. Not a hardcoded file

you expose duplicated data that never changes to the internet like this, everyone forgets about it (or leaves the company) and when and if the values in the DB change, this will break for sure.

this repo also has different concerns and it seems like it might become a bucket for "this random piece of data we need to expose to the clients"

but if mark and pablo greenlighted it I can get out of the way

**Comment by ndcotta-bc** [comment]
It is worth adding clients do not actually ever call this repo. They call an http server (nabu assets) which reads from here.

So when github goes down, clients don't, and they have nothing hardcoded about this repo. You will be introducing a new hard dependency here if you make clients look here.

We are also not in control of the responses from github. If we want to introduce http caching, rate limiting, IP blacklisting, change CORS, etc we cannot. We have zero visibility (grafana, datadog...) on the latency, rps, etc to this repo.

**Comment by matsjj** [comment]
Sorry if this wasn't clear!
The intention was to use this file as an input to nabu assets, which would then serve the data to the clients. 

I agree that the service that reads the value straight from the database would be nice. But the downside is adding a public endpoint to an otherwise very locked-up service that doesn't even listen to HTTP currently (hot-wallet)

**Comment by ndcotta-bc** [comment]
oh if you are looking to extend assets that changes things yes.

imho this is _still_ data that should probably not live here. If you want to involve nabu-assets set up a meeting with me, but right now it's likely you'll need to get another nabu eng to do the PR (or do it yourself)

**Pull request closed without merging**
